-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 15:44:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab6` DEFAULT CHARACTER SET utf8 ;
USE `lab6` ;

-- -----------------------------------------------------
-- Table `lab6`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`people` (
  `snp` VARCHAR(45) NOT NULL,
  `dateBirth` DATETIME NOT NULL,
  PRIMARY KEY (`snp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab6`.`letter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`letter` (
  `idletter` INT NOT NULL AUTO_INCREMENT,
  `sender` VARCHAR(45) NOT NULL,
  `receiver` VARCHAR(45) NOT NULL,
  `topic` VARCHAR(20) NOT NULL,
  `text` VARCHAR(300) NOT NULL,
  `dateOfSend` DATETIME NOT NULL,
  PRIMARY KEY (`idletter`),
  INDEX `pepll_idx` (`sender` ASC) VISIBLE,
  CONSTRAINT `pepll`
    FOREIGN KEY (`sender`)
    REFERENCES `lab6`.`people` (`snp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
